rabbit1:
  image: karinakuroda/rabbitmq-federation
  hostname: rabbit1
  environment:
    - ERLANG_COOKIE=abcdefg
  ports:
    - "5682:5672"
    - "15692:15672"
rabbit2:
  image: karinakuroda/rabbitmq-federation
  hostname: rabbit2
  links:
    - rabbit1
  environment:
    - ERLANG_COOKIE=abcdefg
    - CLUSTER_WITH=rabbit1
  ports:
    - "5683:5672"
    - "15693:15672"
rabbit3:
  image: karinakuroda/rabbitmq-federation
  hostname: rabbit3
  links:
    - rabbit1
    - rabbit2
  environment:
    - ERLANG_COOKIE=abcdefg
    - CLUSTER_WITH=rabbit1
  ports:
    - "5684:5672"
    - "15694:15672"
